### PR TITLE
Fix scope vars in fct hide

### PR DESCRIPTION
**Pull request by Fridus**
Can be problematic in a compression

### CODE REVIEW

**Comment by Fridus** [comment]
@object505 Hi, could you merge this PR ? :)

**Comment by Fridus** [comment]
@object505 Have you seen this PR ?

**Comment by Fridus** [comment]
+1

**Comment by Fridus** [comment]
I use your plugin in one of my projects. Could you make a release with my PR plz ?

**Comment by Natsuke** [comment]
+1

**Comment by object505** [comment]
I will merge this pull request over the forthcoming weekend. Sorry for the wait, work overload :)

**Comment by Fridus** [comment]
Thx :)

**Pull request merged**
